### ISSUE TITLE
outdated code merged on March 1

### ISSUE THREAD

**Issue by mskilab** [mskilab/gUtils#11]
ie 

https://github.com/mskilab/gUtils/blob/e701cf5c668094acc928c63131f5228728bad794/R/gUtils.R

likely due to merging of dev/gUtils which was code from summer 2015!! .. multiple functions are "old version", we need to make sure the insides of functions are up to date with my last stable version from Feb 20th

https://github.com/mskilab/gUtils/blob/c9659fbb30f6b33a41535e87d945083ed97c8cb3/R/gUtils.R

**Comment by KhagayN** [comment]
i'll double check.
