### ISSUE TITLE
add back gr.simplify

### ISSUE THREAD

**Issue by mskilab** [mskilab/gUtils#2]
this is not identical to streduce --> it collapses ranges in gr that are adjacent in gr & adjacent in genome +/- pad & (optional) match in field f

**Comment by jwalabroad** [comment]
Does any downstream code use this? I removed from this version as one less thing to maintain since I didn't see any dependencies.

**Comment by mskilab** [comment]
Jabba uses this and also gChain.  It's also a functionality that has broader uses.  

eg for copy number segment merging, you add a metadata value to denote segments that belong to a set and gr.simplify will reduce only within groups.  

Also if we we represent paths on a reference-aligned assembly as a granges, gr.simplify will collapse all reference / strand adjacent consecutive granges into a single object

**Comment by jwalabroad** [comment]
Ok great. done.
