### ISSUE TITLE
delete %^% and %*%

### ISSUE THREAD

**Issue by jwalabroad** [mskilab/gUtils#3]
These are equivalent to GenomicRanges::%in% and GenomicRanges::findOverlaps, as they don't take the additional arguments that give gr.findoverlaps value anymore (e.g. "by"). I propose that downstream code should use %in% unless it really needs the "by", in which case it should explicitly call gr.findoverlaps.

The issue is that if you just want the query.id and subject.id, then the added overhead of getting the output GRanges in gr.findoverlaps increases compute by 5x, and you shouldn't use %*% but rather findOverlaps. Alternatively, we could keep %* % as syntactic sugar to findOverlaps

**Comment by mskilab** [comment]
x %*% y is a natural join between the meta data of x and y with coordinates as the primary key, its a specific setting of gr.findoverlaps, the goal is not speed but feature merging and quickly piping to other granges functions when doing exploratory analysis

%^% is like %over% but should be more robust to seqinfo / genome mismatches between gr1 and gr2 -> this aspect of %over% %in% etc is often a problem

**Comment by jwalabroad** [comment]
"natural join between the meta data of x and y with coordinates as the primary key"
OK great, I'm seeing it now -- I'll add back, thanks!

Can you provide an example (for me or for end-user) of where %in% and %over% fail because of seqinfo mismatching? It's not clear right now when to use %^%, %in% and %over%

It sounds like gr.in should actually be called gr.over? And a gUtils %in% is actually not written yet?

**Comment by KhagayN** [comment]
I could work on finding examples of when certain operators should be used instead of others.

**Comment by jwalabroad** [comment]
Thanks! That would be very useful. The piping aspect of these vs a normal function call is also a nice way to think of the utility of these.
