### ISSUE TITLE
add back gr.bind and grl.bind

### ISSUE THREAD

**Issue by mskilab** [mskilab/gUtils#7]
these are both very useful - used when c() breaks e.g. when metadata don't match exactly, i.e. like rrbind for GRanges or GRangesList

**Comment by jwalabroad** [comment]
These are grlbind and grbind, and they are already there. Should we add the period back?

**Comment by stevenschumacher** [comment]
Don't name changes like this break existing code?

**Comment by mskilab** [comment]
usually yes .. :) 

however in this case, it wouldn't break existing code if the existing code loads skitools and skitools contains the aliases 

Jeremiah (our local CRAN representative) would like a really slick minimal version of this package .. so we need to "strimline" (streamline + trim) a lot of stuff.   Using skitools as a dumping ground is one approach for preventing downstream code from breaking while putting in relatively radical changes

**Comment by stevenschumacher** [comment]
got it.
