### ISSUE TITLE
grdt vs gr2dt

### ISSUE THREAD

**Issue by mskilab** [mskilab/gUtils#9]
grdt is an elaborate hack but the reason I wrote it is because there are times when gr2dt takes an eternity due to "as.data.frame" operating on granges that have BioStrings as a field

also a ton of my downstream code (Jabba, fish.hook) uses grdt

I suggest putting it back with a flag

**Comment by mskilab** [comment]
for the time being I put grdt back to skitools - check it out there.  We should try vs gr2dt using a big GRanges with metadata that are Biostrings

**Comment by KhagayN** [comment]
would it be useful to recode grdt to use data tables rather than data frames or does that break code downstream.

**Comment by KhagayN** [comment]
and ill create a tutorial on gr2dt using a big GRanges object.

**Comment by jwalabroad** [comment]
switching to data.table should should generally work (its better than
data.frame).

What is the difference between gr2dt and grdt?

**Comment by KhagayN** [comment]
not sure, Marcin said it's a hack to speed up computation b/c gr2dt takes a while to run. I'll look at the code.

**Comment by jwalabroad** [comment]
Can we merge these two into one? In a case without Biostrings, gr2dt is 38x faster than grdt. Perhaps we can take the Biostrings handling from grdt and put into gr2dt. 

I can try this, I just need a good example with a GRanges with a Biostring.

**Comment by KhagayN** [comment]
wow 38x faster. I like the idea of merging the two and creating a conditional statement in case Biostrings are the input.

**Comment by KhagayN** [comment]
could we just use the "is" function in R to test if the input GRanges is of class Biostring. If so we use the grdt code.

**Comment by jwalabroad** [comment]
Looking more, gr2dt is not really 38x faster, it is probably about the same but without a tiny bit of overhead that comes with grdt. They should scale the same. 

I propose deleting gr2dt (its 3 lines...), and changing name of grdt to gr2dt to be in line with dt2gr. I believe that grdt is more robust

**Comment by jwalabroad** [comment]
Whoops, and grdt was in the code twice... ok set grdt and gr2dt both to the same function (the grdt)

**Comment by imielinski** [comment]
hold on!  we were just playing with it and looks like gr2dt is consistently several times faster, though not as much faster when the GRanges has a BioStrings.  Maybe the GenomicRanges folks sped up their as.data.frame and so the hack is not necessary

**Comment by jwalabroad** [comment]
Well the original gr2dt code is just 
```
  if (any(duplicated(names(gr))))
    names(gr) <- NULL
  out <- as.data.table(GenomicRanges::as.data.frame(gr))
``` 
so if you find that grdt is not necessary for the case you find (DNAStringSet conversion was fine for me with gr2dt), then just replace with the above.

**Comment by imielinski** [comment]
ok let's rename the function to gr2dt and keep this simple code as the first pass but in a tryCatch statement, and then run the grdt code if there is an error 

regarding changing the name .. Khagay can go through the downstream code (including some the gUtils functions) to find replace grdt w gr2dt

**Comment by KhagayN** [comment]
all instances of grdt have been removed in gUtils. there is no use of grdt in gTrack but, in skitools and JaBba there are a few uses of it. I'll work on replacing them with gr2dt and writing test cases.

**Comment by KhagayN** [comment]
updated.
